# Generated by Django 5.0.7 on 2024-07-25 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionKPI',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='identifiant de session')),
                ('auth_username', models.CharField(default=None, max_length=255, null=True, verbose_name="Nom d'utilisateur")),
                ('create_at', models.DateTimeField(default=None, editable=False, null=True, verbose_name='Vue sur le site le')),
                ('urls_count', models.IntegerField(default=0, verbose_name='Nombre de pages visitées')),
                ('unique_urls_count', models.IntegerField(default=0, verbose_name='Nombre de pages uniques visitées')),
                ('is_rebond', models.BooleanField(default=False, verbose_name='Est un rebond')),
                ('session_time', models.DurationField(default=None, null=True, verbose_name='Durée de la session')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_at', models.DateTimeField(auto_now_add=True, verbose_name='Requétée le')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kpi.sessionkpi')),
            ],
            options={
                'verbose_name': 'Historique de la session',
                'verbose_name_plural': 'Historique de la session',
                'ordering': ['get_at'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_row', models.CharField(max_length=255, unique=True)),
                ('url_name', models.CharField(max_length=50)),
                ('sessions', models.ManyToManyField(through='kpi.SessionHistory', to='kpi.sessionkpi')),
            ],
        ),
        migrations.AddField(
            model_name='sessionkpi',
            name='urls',
            field=models.ManyToManyField(through='kpi.SessionHistory', to='kpi.url'),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kpi.url'),
        ),
    ]
