# Generated by Django 5.0.6 on 2024-07-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.session')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.url')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='urls',
            field=models.ManyToManyField(through='kpi.SessionHistory', to='kpi.url'),
        ),
    ]
