# Generated by Django 5.0.6 on 2024-07-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_rename_session_sessionhistory_sessions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionhistory',
            old_name='sessions',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='sessionhistory',
            old_name='urls',
            new_name='url',
        ),
    ]
