# Generated by Django 5.0.6 on 2024-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_rename_sessions_sessionhistory_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='auth_username',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
