# Generated by Django 5.0.6 on 2024-07-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_session_auth_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionhistory',
            options={'ordering': ['get_at']},
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kpi.session'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kpi.url'),
        ),
    ]
