# Generated by Django 5.0.6 on 2024-07-23 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_alter_sessionhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Vue sur le site le'),
            preserve_default=False,
        ),
    ]
