# Generated by Django 5.0.6 on 2024-06-25 11:42

import base.models.animals
import base.models.publication
import base.models.sponsors
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('breed', models.CharField(max_length=50, verbose_name='Race')),
                ('birth', models.DateField(verbose_name='Date de naissance')),
                ('arrival', models.DateField(verbose_name="Date d'arrivé")),
                ('profile', models.ImageField(upload_to=base.models.animals.image_path, verbose_name='Photo de profile')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Protégé',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Home/')),
                ('home_text', models.TextField(default='Bienvenue !', verbose_name="Texte d'accueil")),
                ('location', models.CharField(default='6 rue des fleurs 17589 Queleque_part', max_length=255, verbose_name='Adresse')),
                ('phone_number', models.CharField(default='+33 (0)6 11 22 33 44', max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(default='contact@exemple.com', max_length=254, verbose_name='e-mail')),
                ('opening_hours', models.TextField(default='\n✅ Lun 10h-19h\n✅ Mar 10h-19h\n✅ Mer 10h-19h\n✅ Jeu 10h-19h\n✅ Ven 10h-19h\n❌ Sam férmé\n❌ Dim férmé\n', verbose_name="Horaire d'ouverture")),
            ],
            options={
                'verbose_name': 'Accueil',
                'verbose_name_plural': 'Accueil',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('post_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.FileField(upload_to=base.models.sponsors.logo_path, validators=[django.core.validators.FileExtensionValidator(['svg', 'webp', 'png', 'jpg', 'jpeg', 'png'])])),
                ('website', models.CharField(max_length=255, unique=True, verbose_name='Site Web')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=base.models.publication.image_path, verbose_name='Média')),
                ('file_type', models.CharField(editable=False, max_length=1, verbose_name='Type de média')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='base.publication')),
            ],
            options={
                'verbose_name': 'Média',
            },
        ),
    ]
