# Generated by Django 5.0.6 on 2024-06-13 16:40

import base.models.sponsors
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(upload_to=base.models.sponsors.image_path)),
            ],
        ),
    ]
