# Generated by Django 5.0.6 on 2024-06-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='detail',
            field=models.CharField(default='', max_length=50, verbose_name='Détail'),
            preserve_default=False,
        ),
    ]
