# Generated by Django 5.0.7 on 2024-08-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='adoption_text',
            field=models.TextField(blank=True, verbose_name="texte d'adoption"),
        ),
    ]
