# Generated by Django 5.0.6 on 2024-06-19 13:16

import base.models.animals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('breed', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('arrival', models.DateField()),
                ('profile', models.ImageField(upload_to=base.models.animals.image_path)),
                ('description', models.TextField()),
            ],
        ),
    ]
