# Generated by Django 5.0.6 on 2024-06-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('post_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='publications/', verbose_name='Média')),
                ('file_type', models.CharField(choices=[('P', 'Photo'), ('V', 'Video')], default='P', max_length=1, verbose_name='Type de média')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attachments', to='base.publication')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
    ]
