# Generated by Django 5.0.6 on 2024-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sponsor_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_first_of_month',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='detail',
            field=models.CharField(default='', max_length=50, verbose_name='Détail'),
        ),
    ]
