# Generated by Django 5.0.6 on 2024-06-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_publication_publicationattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationattachment',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='publicationattachment',
            name='file',
            field=models.FileField(upload_to='publications/', verbose_name='Média'),
        ),
    ]
