# Generated by Django 5.0.6 on 2024-07-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_publication_is_first_of_month_alter_sponsor_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['post_at']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='is_first_of_month',
            new_name='is_last_of_month',
        ),
    ]
