# Generated by Django 5.0.6 on 2024-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-post_at']},
        ),
        migrations.AddField(
            model_name='home',
            name='home_picture',
            field=models.ImageField(null=True, upload_to='Home/', verbose_name="Image d'accueil"),
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_last_of_month',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
