# Generated by Django 5.0.6 on 2024-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_publicationattachment_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationattachment',
            name='file_type',
            field=models.CharField(default='Photo', editable=False, max_length=1, verbose_name='Type de média'),
            preserve_default=False,
        ),
    ]
