# Generated by Django 5.0.6 on 2024-06-20 14:56

import base.models.publication
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_publicationattachment_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Home/')),
                ('home_text', models.TextField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='publicationattachment',
            name='file',
            field=models.FileField(upload_to=base.models.publication.image_path, verbose_name='Média'),
        ),
        migrations.AlterField(
            model_name='publicationattachment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='base.publication'),
        ),
    ]
