# Generated by Django 5.0.6 on 2024-07-11 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_publication_options_home_home_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_picture',
            field=models.FileField(null=True, upload_to='Home/', verbose_name="Image d'accueil"),
        ),
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.ImageField(upload_to='Home/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
