# Generated by Django 5.0.6 on 2024-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_home_home_picture_alter_home_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_picture',
            field=models.FileField(blank=True, null=True, upload_to='Home/', verbose_name="Image d'accueil"),
        ),
    ]
