# Generated by Django 5.0.6 on 2024-06-20 18:09

import base.models.animals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_home_alter_publicationattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Protégé'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Accueil', 'verbose_name_plural': 'Accueil'},
        ),
        migrations.AlterModelOptions(
            name='publicationattachment',
            options={'verbose_name': 'Média'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='website',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Site Web'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival',
            field=models.DateField(verbose_name="Date d'arrivé"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='birth',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=50, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='profile',
            field=models.ImageField(upload_to=base.models.animals.image_path, verbose_name='Photo de profile'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_text',
            field=models.TextField(verbose_name="Texte d'accueil"),
        ),
        migrations.AlterField(
            model_name='home',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
