# Generated by Django 5.0.6 on 2024-06-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_animal_options_alter_home_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.EmailField(default='contact@exmple.com', max_length=254, verbose_name='e-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='phone_number',
            field=models.CharField(default='+33 (0)6 11 22 33 44', max_length=20, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
    ]
