# Generated by Django 5.0.6 on 2024-07-11 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_home_home_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='logo',
            field=models.FileField(upload_to='Home/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Logo (en .SVG uniquement)'),
        ),
    ]
