# Generated by Django 5.0.6 on 2024-06-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_home_email_home_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='opening_hours',
            field=models.TextField(default='', verbose_name="Horaire d'ouverture"),
            preserve_default=False,
        ),
    ]
