# Generated by Django 5.0.7 on 2024-07-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_publicationattachment_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='detail',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Détail'),
        ),
    ]
