# Generated by Django 5.0.7 on 2024-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_sponsor_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Détail'),
        ),
    ]
